### ISSUE TITLE
Bug -  tf-next - 'yarn' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by RomainBillot** [milliHQ/terraform-aws-next-js#264] opened 2022-01-21 20:14 UTC
Hi,

I do have yarn installed :
```
Z:\iziowebsite\packages>where yarn
C:\Program Files\nodejs\yarn
C:\Program Files\nodejs\yarn.cmd
```

But I'm using `pnpm` as my package manager. And this seems to be an issue, in fact, running `pnpm tf-next` where this script is defined as `"tf-next": "tf-next build"` in the `package.json` cause this issue : `'yarn' is not recognized as an internal or external command`.

Is anyone having the same issue?

**Comment by ofhouse** [comment] 2022-01-21 20:48
Hi, seems like this is the same error as in #256.
Could reproduce it, but cannot say when I have time to investigate this further.

**Comment by RomainBillot** [comment] 2022-01-21 23:08
Hi again,

I've checked my node version : `v16.13.0`. Should be ok, no?

**Comment by ofhouse** [comment] 2022-01-23 14:22
> I've checked my node version : `v16.13.0`. Should be ok, no?
Sorry, some comments in the linked issue are misleading.
Only the first 4 comments are describing the issue, the other comments about Node.js version are not relevant for the issue.

The issue is Windows specific but has nothing to do with the used Node.js version (AFAIK).

**Comment by IzioDev** [comment] 2022-02-24 19:01
I do not have (and don't want) yarn installed on my machine. I use 'pnpm' and can't use yarn, in fact, the way they defines workspaces aren't the same, and hence, not working if using yarn.

Do you plan supporting 'pnpm' out of the box ?

**Comment by R-Bower** [comment] 2022-04-30 19:31
pnpm is the fastest package manager out there, at least for Node projects.  I hope this repo can implement support for it soon!

**Comment by ofhouse** [comment] 2022-05-01 17:57
Since the issue contains multiple problems, I've created a tracking issue for pnpm support here: #309
The original problem is tracked here, since it is a duplicate of: #256

Two words on pnpm: Should be easy to implement, since the underlying Vercel toolchain already supports it:
https://github.com/vercel/vercel/blob/a400b9b29d171232f4649e67e1fdcf4fb8d6a4c8/packages/build-utils/src/fs/run-user-scripts.ts#L293
However I am currently busy implementing the multi deployments feature, so pnpm support is deferred until the feature is shipped.

**Closed by ofhouse** 2022-05-01 17:57 UTC
Labels: duplicate
