### ISSUE TITLE
[BUG] Lamda API Error using unstable_revalidate

### ISSUE THREAD

**Issue by mohalsherif** [milliHQ/terraform-aws-next-js#313] opened 2022-05-09 20:33 UTC
We wanted to introduce the new NextJs `unstable_revalidate` feature (See [here](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation)). However, we are having some errors with the api lambda that is revalidating this page. The error that we see in the AWS lambda logs is the following:
```
INFO	revalidate error Error: Failed to revalidate /abc/def: Invariant: required internal revalidate method not passed to api-utils
    at unstable_revalidate (/var/task/node_modules/next/dist/server/api-utils/node.js:247:15)
    at ServerResponse.apiRes.unstable_revalidate (/var/task/node_modules/next/dist/server/api-utils/node.js:175:55)
    at handler (/var/task/.next/serverless/pages/api/revalidate.js:161:15)
    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:185:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /var/task/.next/serverless/chunks/884.js:42:13
``` 
However this is working locally with `next start`, so we are pretty sure its stable, but we are not sure what is missing on the lambda side. 

Also we found a similar issue in some other nextjs library ([serverless-nextjs](https://github.com/serverless-nextjs/serverless-next.js/issues/2417)) that might be related, but its not clear to us.

We also traced down the error to the specific nextjs [line](https://github.com/vercel/next.js/blob/canary/packages/next/server/api-utils/node.ts#L346). Locally, we would have the `context.revalidate` set and hence the error does not occur. We are not sure why it is not set on the lambda. 

Any indications would be great. Thank you

**Comment by khuezy** [comment] 2022-05-10 02:33
I don't think Incremental Static Regeneration is currently supported yet. I looks like it's on the roadmap, but it might be awhile for the feature to get released.

**Comment by mohalsherif** [comment] 2022-05-10 04:25
Ohh you are right. I see the feature is being discussed [here](https://github.com/milliHQ/terraform-aws-next-js/issues/11). So this means that the normal `revalidate` is not even implemented yet. Is there any workaround that would be currently possible for us here? I tried removing the s3 file that we want to regenerate, but that does not trigger the lambda off course.

**Comment by ofhouse** [comment] 2022-05-10 11:50
Hi, no workaround is currently available to enable ISR.
The Lambdas currently have no access to the S3 files, so they cannot determine at runtime wether a file exists or if it needs to be generated.
The multiple deployment branch has an implementation that changes that, so that a lookup is possible.

Once the multiple deployments feature is released I will take a closer look how ISR could be implemented.
The flow will be something like:
![Frame 1](https://user-images.githubusercontent.com/472867/167621295-b9da5934-af4b-4bb9-9a4e-2e1203ede1c8.png)

However this requires additional roundtrips which heavily impact the overall performance.
Without caching I would expect a response time > 5 sec for a non-fallback ISR route.

**Comment by khuezy** [comment] 2022-05-10 13:32
Does that mean the user w/ the stale request has to deal w/ the long response time, or will they get the cached response while the regeneration happens in the background?

**Comment by ofhouse** [comment] 2022-05-10 14:19
No, the regeneration will be asynchronous for stale responses `fallback: true`.
For that case I think we will see response times between 30-300ms, which will be the default response time for static files served by S3.

Worst case I am speaking of here is when `fallback: 'blocking'` is set.
That means the whole regeneration process runs synchronous and the response time depends on cold start times of multiple Lambdas (could be up to 4 in this scenario) in the worst case.

**Comment by ofhouse** [comment] 2022-05-28 13:14
Closing this as a duplicate of #11.

**Closed by ofhouse** 2022-05-28 13:14 UTC
Labels: question
